# Generated by Django 3.1.4 on 2020-12-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaneOsobowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1)),
                ('dataUrodzenia', models.DateField()),
                ('kraj', models.CharField(max_length=100)),
                ('wojewodztwo', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('kodPocztowy', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=100)),
                ('numerTelefonu', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Dok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('iloscMiejsc', models.IntegerField()),
                ('kraj', models.CharField(max_length=100)),
                ('wojewodztwo', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('narzedzia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PojazdMiejski',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typNapedu', models.CharField(choices=[('zwykły', 'Zwykly'), ('elektryczny', 'Elektryczny'), ('hybryda', 'Hybryda')], max_length=20)),
                ('rodzaj', models.CharField(choices=[('rower', 'Rower'), ('hulajnoga', 'Hulajnoga'), ('skuter', 'Skuter')], max_length=20)),
                ('kolor', models.CharField(max_length=45)),
                ('kodSprzetu', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Stawka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stawka', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataStart', models.DateField()),
                ('dataStop', models.DateField()),
                ('idDaneOsobowe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPM.daneosobowe')),
                ('idPojazdMiejski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPM.pojazdmiejski')),
            ],
        ),
        migrations.CreateModel(
            name='Rozliczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wplata', models.DecimalField(decimal_places=2, max_digits=13)),
                ('idStawka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPM.stawka')),
                ('idWypozyczenia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPM.wypozyczenia')),
            ],
        ),
        migrations.CreateModel(
            name='PojazdyWDokac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPM.dok')),
                ('idPojazdMiejski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPM.pojazdmiejski')),
            ],
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szerokoscGeograficzna', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dlugoscGeograficzna', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ostatniaAktualizacja', models.DateTimeField()),
                ('idPojazdMiejski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPM.pojazdmiejski')),
            ],
        ),
    ]
